version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_IP=mongo
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - SESSION_SECRET=secret
    command: npm run dev
  nginx:
    ports:
      - "3000:80"
